---
- hosts: worker-machine
  vars:
    run: bash -x deploy-script.sh
    remote_project_path: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/arrebol/"
    services_path: "../../services"
    services_conf_files_path: "{{ services_path }}/conf-files"
    worker_service_path: " {{ services_path }}/worker"
  tasks:
    - name: Copy files
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ remote_project_path }}"
      with_items:
        - "{{ services_conf_files_path }}/worker-conf.json"
        - "{{ worker_service_path }}/deploy-script.sh"

    - name: Run
      shell: "{{ run }}"
      become: yes
      args:
        chdir: "{{ remote_project_path }}"