---
- hosts: server-machine
  vars:
    run: bash -x deploy-script.sh
    remote_project_path: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/arrebol-server/"
    services_path: "../../services"
    server_conf_files_path: "{{ services_path }}/conf-files/server"
    server_service_path: "{{ services_path }}/server"
  tasks:
    - name: Copy files
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ remote_project_path }}"
      with_items:
        - "{{ server_conf_files_path }}/allowlist"
        - "{{ server_conf_files_path }}/.env"
        - "{{ server_conf_files_path }}/keys"
        - "{{ server_service_path }}/deploy-script.sh"
        - "{{ server_service_path }}/docker-stack.yaml"

    - name: Run
      shell: "{{ run }}"
      become: yes
      args:
        chdir: "{{ remote_project_path }}"