version: "3.7"

services:
  db:
    image: postgres:13
    env_file:
      - ./.env
    networks:
      - net
    ports:
      - "5432:5432"
    volumes:
      db:/var/lib/postgresql/data
  dba:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "arrebol@lsd.ufcg.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      net
    ports:
      - 80:80

  server:
    image: raonismaneoto/arrebol-server:latest
    env_file:
      - ./.env
    networks:
      - arrebol-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "5000:5000"
    volumes:
      allowlist:
      keys:

volumes:
  db: {}

networks:
  net:
    driver: overlay
